apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-server
  template:
    metadata:
      labels:
        app: data-server
    spec:
      containers:
        - name: data-server
          image: data-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: data-server
spec:
  selector:
    app: data-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
